version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  yarn:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn
      - run: yarn test

  lint:
    executor: node
    steps:
      - checkout
      - yarn
      - run: yarn lint

  coverage:
    executor: node
    steps:
      - checkout
      - yarn
      - run: yarn coverage
      - run: yarn coveralls
  
  publish-to-npm:
    executor: node
    steps:
      - checkout
      - yarn
      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$BOOPBOT_NPM_TOKEN" >> ~/.npmrc
            VERSION=`yarn info . version --silent`-`git rev-parse --short HEAD`-`date +'%m-%d-%Y'`
            yarn version --new-version=${VERSION}
            if [ -z $CIRCLE_PR_NUMBER ]; then
              TAG=pull-request-${PR_NUMBER}
              yarn publish --tag=${TAG}
              echo $TAG > NPM_TAG
            else
              [[ -v $CIRCLE_BRANCH == "master" ]]; yarn publish --tag=head
            fi
      - persist_to_workspace:
          root: .
          paths:
            - NPM_TAG


workflows:
  version: 2.1
  build:
    jobs:
      - test
      - lint
      - coverage
      - publish-to-npm:
          requires:
            - test


